### ISSUE TITLE
편의성 및 에러 수정

### ISSUE THREAD

**Issue by kangkyeongseo** [kangkyeongseo/next-caffeine-station#18]
### Todo

- [x] 위치 재검색후 지도 조작 시  지도에 재검색한 위치의 잔상이 남음
- [x] 검색 결과 없을 시 무한 로딩 에러
- [x] 커스텀 오버레이 클릭 시 해당 카페 페이지로 이동 안하는 에러
- [x] 위치 검색시 중심 위치 마크 표시
- [x] 거리별 검색 시 중심을 기준으로 맵을 바운딩 
- [x]  키워드 변경 시 전역 키워드 변경
- [x]  로그아웃시 키워드 미변경
- [x]  키워드 변경 시 rule 정보 삭제되는 이슈
- [x] 위치 변경 시 기존의 위치로 검색되는 이슈
- [x] 특정 카페 키워드가 매장별로 다른 이슈
