### ISSUE TITLE
인증 기능 추가

### ISSUE THREAD

**Issue by kangkyeongseo** [kangkyeongseo/next-caffeine-station#20]
### Todo

- [x] 인증 관련 UI 제작
- [x] 파이어베이스 인증 연동
- [x] 어드민 페이지 인증에 따른 제한
- [x] 카페 카테고리 필터의  카페 수정 기능 추가
- [x] 카페 카테고리 필터의  카페 수정 인증에 따른 제한
- [x] URL를 통해 auth 페이지 접근 후 쿼리스트링이 다른 페이지로 이동 시 모달로 생성되는 이슈
