### ISSUE TITLE
리팩토링 및 성능 개선

### ISSUE THREAD

**Issue by kangkyeongseo** [kangkyeongseo/next-caffeine-station#23]
### Todo

- [x] 비동기 방식의 카페 검색 리팩토링
- [x] Firebase 관련 모듈 동적 라우팅을 통한 First Load JS 크기 감소
- [x] Firebase 관련 모듈이 포함된 컴포넌트 Lazy Loading을 통한 First Load JS 크기 감소
- [x] Auth 페이지 로딩 UI 및 스켈레톤 UI 적용
