### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by kangkyeongseo** [kangkyeongseo/next-caffeine-station#9]
### Todo

- [x] 필터링 컴포넌트 UI 및 기능 개선
- [x] 카페 리스트 UI 및 기능 개선
- [x] 지도상의 커스텀 오버레이 UI 및 기능 개선
- [x] 로딩 페이지 UI 및 기능 개선
